import Head from 'next/head'
import { Inter } from '@next/font/google'
import NavBar from '@/components/NavBar';
import Hero from '@/components/Hero';
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  return (
    <>
      <Head>
        <title>RLSWW Custom Watches</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">

        {/* Hero */}
        <Hero />

        {/* Core Product Line | View Collection*/}
        {/* Customer Reviews */}
        {/* Footer */}
      </main>
    </>
  )
}
