import Head from 'next/head'
import { Inter } from '@next/font/google'
import Hero from '@/components/Hero';
import CollectionModule from '../components/CollectionModule'
import { collectionQuery } from '../lib/storefront'
import * as React from 'react';
import Footer from '../components/Footer'


// const inter = Inter({ subsets: ['latin'] })

export async function getStaticProps() {
  const allCollections = await collectionQuery();
  return {
    props: {
      allCollections,
    },
  };
}


export default function Home({ allCollections }) {
  console.log(allCollections)
  return (
    <div>
      <Head>
        <title>RLSWW Custom Watches</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">

        {/* Hero */}
        <Hero />

        {/* Collections */}
        {
          allCollections.map((collection, id)=>(
            <CollectionModule collection={collection.node} orientation={id}/>
          ))
        }

        {/* Footer */}
        <Footer />

      </main>
    </div>
  )
}

