import Head from 'next/head'
import { Inter } from '@next/font/google'
import Hero from '@/components/Hero';
import * as React from 'react';
import { shopifyClient, parseShopifyResponse } from '../lib/shopify';


// const inter = Inter({ subsets: ['latin'] })

export const getServerSideProps = async () => {
	// Fetch all the products
	const products = await shopifyClient.product.fetchAll();
	return {
		props: {
			products: parseShopifyResponse(products),
		},
	};
};


export default function Home({products}) {
  return (
    <>
      <Head>
        <title>RLSWW Custom Watches</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">

        {/* Hero */}
        <Hero />

        {/* Core Product Line | View Collection*/}
        {/* Customer Reviews */}
        {/* Footer */}
      </main>
    </>
  )
}